version: "3.9"

services:
  api:
    build: .
    container_name: secure_rest_api_prod
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    environment:
      - ENV=prod
    volumes:
      - app_data:/data     # mount /data for persistent DB storage
    restart: unless-stopped

volumes:
  app_data:
